escape_hither_security_login:
    path:     /login
    defaults: { _controller: EscapeHitherSecurityManagerBundle:Security:login }
escape_hither_security_logout:
    path:     /logout
    defaults: { _controller: EscapeHitherSecurityManagerBundle:Security:logOut }
escape_hither_user_registration:
    path:     /register
    defaults: { _controller: EscapeHitherSecurityManagerBundle:Registration:register }

escape_hither_user_profile:
    path:     /profile
    defaults: { _controller: EscapeHitherSecurityManagerBundle:Profile:edit }

escape_hither_api_token:
    path:     /api/login
    defaults:
        _controller: "EscapeHitherSecurityManagerBundle:Token:newToken"
    methods: [POST,GET]

escape_hither_api_login_check:
    path: /api/login_check

