security_login:
    path:     /login
    defaults: { _controller: EscapeHitherSecurityManagerBundle:Security:login }
security_logout:
    path:     /logout
    defaults: { _controller: EscapeHitherSecurityManagerBundle:Security:logOut }
user_registration:
    path:     /register
    defaults: { _controller: EscapeHitherSecurityManagerBundle:Registration:register }

user_profile:
    path:     /profile
    defaults: { _controller: EscapeHitherSecurityManagerBundle:Profile:edit }

api_token:
    path:     /api/login
    defaults:
        _controller: "EscapeHitherSecurityManagerBundle:Token:newToken"
    methods: [POST,GET]

api_login_check:
    path: /api/login_check


starter_kit_manage_user:
        resource: "@EscapeHitherSecurityManagerBundle/Resources/config/routing/user.yml"
        prefix:   /admin/user