services:
   starter_kit_security_manager.login_form_authenticator:
       class: StarterKit\SecurityManagerBundle\Security\LoginFormAuthenticator
       #autowire: true
       arguments : ['@form.factory','@doctrine.orm.entity_manager','@router','@security.user_password_encoder.generic','%starter_kit.security.user.class%']

   starter_kit_security_manager.doctrine.hash_password_listener:
          class: StarterKit\SecurityManagerBundle\Doctrine\HashPasswordListener
          autowire: true
          tags:
              - { name: doctrine.event_subscriber }

   starter_kit_security_manager.form.edit_roles:
            class: StarterKit\SecurityManagerBundle\Form\EditUserRoles
            arguments: ['%security.role_hierarchy.roles%']
            tags:
                - { name: form.type }
   starter_kit_security_manager.jwt_token_authenticator:
            class: StarterKit\SecurityManagerBundle\Security\JwtTokenAuthenticator
            #autowire: true
            arguments : ['@lexik_jwt_authentication.encoder','@doctrine.orm.entity_manager','@router','@security.user_password_encoder.generic','%starter_kit.security.user.class%']